### ISSUE TITLE
terraform-docs pre-hook

### ISSUE THREAD

**Issue by ElfoLiNk** [bitrockteam/caravan-infra-gcp#37]
`brew install pre-commit gawk terraform-docs tflint tfsec coreutils`

per i nuovi repo git:

```
DIR=~/.git-template
git config --global init.templateDir ${DIR}
pre-commit init-templatedir -t pre-commit ${DIR}
```

Su questo repository:

```
cat <<EOF > .pre-commit-config.yaml
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.45.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
EOF
```

`pre-commit install` per installare pre-commit nel repo attuale

Aggiungere al README.md :

```
<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->

<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
```

Se necessario eseguire manualmente `pre-commit run -a` o modificare un file terraform
